In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
filename = r"C:\Users\BenBuczek\OneDrive - KIPP New Orleans, Inc\Desktop\Springboard\capstone_2.2_diamond_data.csv"
data = pd.read_csv(filename)
data.head().T

,0,1,2,3,4
cut,Round,Round,Round,Round,Round
color,E,E,E,E,E
clarity,VVS2,VVS2,VVS2,VVS2,VVS2
carat_weight,0.09,0.09,0.09,0.09,0.09
cut_quality,Excellent,Very Good,Excellent,Excellent,Very Good
lab,IGI,IGI,IGI,IGI,IGI
symmetry,Very Good,Very Good,Very Good,Very Good,Very Good
polish,Very Good,Very Good,Very Good,Very Good,Excellent
culet_size,N,N,unknown,unknown,N
depth_percent,62.7,61.9,61.1,62.0,64.9
table_percent,59.0,59.0,59.0,59.0,58.5
meas_length,2.85,2.84,2.88,2.86,2.79
meas_width,2.87,2.89,2.9,2.88,2.83
meas_depth,1.79,1.78,1.77,1.78,1.82
fluor_intensity,None,None,None,None,None
total_sales_price,200,200,200,200,200
price_per_carat,2222.222222,2222.222222,2222.222222,2222.222222,2222.222222

In [3]:
numeric_data = data.select_dtypes(include=['float64', 'int64'])
categorical_data = data.select_dtypes(include=['object'])

In [4]:
categorical_data.columns.unique()

Index(['cut', 'color', 'clarity', 'cut_quality', 'lab', 'symmetry', 'polish',
       'culet_size', 'fluor_intensity'],
      dtype='object')

In [5]:
# Selecting nominal columns
nominal_cols =['cut', 'color', 'clarity', 'cut_quality', 'lab', 'symmetry', 'polish', 'culet_size', 'fluor_intensity']

# Initialize the encoder
onehot_encoder = OneHotEncoder(sparse_output=False)

# Encode the nominal data
encoded_nominal = onehot_encoder.fit_transform(data[nominal_cols])

# Convert the encoded data into a DataFrame
encoded_nominal_df = pd.DataFrame(encoded_nominal, columns=onehot_encoder.get_feature_names_out(nominal_cols))

# Concatenate with the original DataFrame
data = pd.concat([data, encoded_nominal_df], axis=1).drop(nominal_cols, axis=1)

In [6]:
numeric_data.head()

,carat_weight,depth_percent,table_percent,meas_length,meas_width,meas_depth,total_sales_price,price_per_carat
0,0.09,62.7,59.0,2.85,2.87,1.79,200,2222.222222
1,0.09,61.9,59.0,2.84,2.89,1.78,200,2222.222222
2,0.09,61.1,59.0,2.88,2.90,1.77,200,2222.222222
3,0.09,62.0,59.0,2.86,2.88,1.78,200,2222.222222
4,0.09,64.9,58.5,2.79,2.83,1.82,200,2222.222222

In [7]:
data = data.rename(columns={'total_sales_price': 'target_price', 'price_per_carat': 'target_ppc'})

In [8]:
#turns out i dont really want it
data = data.drop(['target_ppc'], axis=1)

In [9]:
numeric_cols = [col for col in data.columns if data[col].dtype in ['int64', 'float64'] and col != 'target_1']

# Initialize the scaler
scaler = StandardScaler()

# Scale the numeric data
data[numeric_cols] = scaler.fit_transform(data[numeric_cols])

In [10]:
data.head().T

                                    0         1         2         3         4
carat_weight                -0.786360 -0.786360 -0.786360 -0.786360 -0.786360
depth_percent                0.102492  0.021808 -0.058876  0.031894  0.324373
table_percent                0.125746  0.125746  0.125746  0.125746  0.075544
meas_length                 -1.530031 -1.535701 -1.513024 -1.524362 -1.564047
meas_width                  -1.648296 -1.633745 -1.626470 -1.641020 -1.677397
...                               ...       ...       ...       ...       ...
fluor_intensity_Slight      -0.007391 -0.007391 -0.007391 -0.007391 -0.007391
fluor_intensity_Strong      -0.253265 -0.253265 -0.253265 -0.253265 -0.253265
fluor_intensity_Very Slight -0.112150 -0.112150 -0.112150 -0.112150 -0.112150
fluor_intensity_Very Strong -0.070709 -0.070709 -0.070709 -0.070709 -0.070709
fluor_intensity_unknown     -0.024144 -0.024144 -0.024144 -0.024144 -0.024144

[76 rows x 5 columns]

In [11]:
# Features and target
X = data.drop('target_price', axis=1) 
y = data['target_price']             

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2,
    random_state=42
)

In [12]:
data.to_csv(r"C:\Users\BenBuczek\OneDrive - KIPP New Orleans, Inc\Desktop\Springboard/capstone_2.3_diamond_data.csv", index=False)